# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('body', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
