# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170423_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Photography', 'Photography'), ('Tech', 'Tech')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
