# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 02:58
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170502_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=''),
        ),
    ]
