# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
