# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20170818_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='photo_thumb',
            new_name='photo_small',
        ),
    ]
