# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemShopSpecials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
                ('item_url', models.URLField()),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
